export const profAvatar = JSON.stringify({
  skinTone: "dark",
  eyes: "content",
  eyebrows: "leftLowered",
  mouth: "grin",
  hair: "balding",
  facialHair: "none3",
  clothing: "dressShirt",
  accessory: "roundGlasses",
  graphic: "none",
  hat: "beanie",
  body: "chest",
  hairColor: "brown",
  clothingColor: "white",
  circleColor: "blue",
  lipColor: "purple",
  hatColor: "red",
  faceMaskColor: "blue",
  mask: true,
  faceMask: false,
  lashes: true,
});
